---
template_path: veoibd.yaml
stack_name: veoibd-develop
parameters:
  ComputeImageId: ami-082278746f893d99c
  MainContainer: sagebionetworks/veoibd-validation-docker:latest
  Department: "SysBio"
  Project: "veoibd"
  OwnerEmail: "kenneth.daily@sagebase.org"
  VpcName: "sandcastlevpc"
