---
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Batch jobs for VEOIBD data validation.

Parameters:
  ComputeImageId:
    Description: The Genie compute resource image ID
    Type: 'AWS::EC2::Image::Id'
  MainImage:
    Description: The Genie main processing and validation docker container image
    Type: String
  Department:
    Description: 'The department for this resource'
    Type: String
    AllowedPattern: '^\S*$'
    ConstraintDescription: 'Must be string with no spaces'
  Project:
    Description: 'The name of the project that this resource is used for'
    Type: String
    AllowedPattern: '^\S*$'
    ConstraintDescription: 'Must be string with no spaces'
  OwnerEmail:
    Description: 'Email address of the owner of this resource'
    Type: String
    AllowedPattern: '^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$'
    ConstraintDescription: 'Must be an acceptable email address syntax(i.e. joe.smith@sagebase.org)'

Resources:
  BatchServiceRole:
    Type: "AWS::IAM::Role"
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSBatchServiceRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: batch.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: "/"
  BatchInstanceRole:
    Type: "AWS::IAM::Role"
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: "/"
  BatchInstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Path: "/"
      Roles:
        - !Ref BatchInstanceRole
  BatchComputeEnvironment:
    Type: "AWS::Batch::ComputeEnvironment"
    Properties:
      Type: MANAGED
      ServiceRole: !GetAtt BatchServiceRole.Arn
      State: ENABLED
      ComputeResources:
        Type: EC2
        MaxvCpus: 256
        SecurityGroupIds:
          - !ImportValue us-east-1-computevpc-VpnSecurityGroup
        Subnets:
          - !ImportValue us-east-1-computevpc-PrivateSubnet
          - !ImportValue us-east-1-computevpc-PrivateSubnet1
          - !ImportValue us-east-1-computevpc-PrivateSubnet2
        MinvCpus: 0
        ImageId: !Ref ComputeImageId
        InstanceRole: !GetAtt BatchInstanceProfile.Arn
        InstanceTypes:
          - optimal
        DesiredvCpus: 8
        Tags:
          "Name": !Sub '${AWS::StackName}-BatchComputeEnvironment'
          "Department": !Ref Department
          "Project": !Ref Project
          "OwnerEmail": !Ref OwnerEmail
  BatchJobQueue:
    Type: "AWS::Batch::JobQueue"
    Properties:
      JobQueueName: !Join
        - '-'
        - - !Ref AWS::StackName
          - "job"
          - "queue"
      ComputeEnvironmentOrder:
        - ComputeEnvironment: !Ref BatchComputeEnvironment
          Order: 1
      Priority: 1
      State: ENABLED
  MainBatchJob:
    Type: 'AWS::Batch::JobDefinition'
    Properties:
      Type: container
      JobDefinitionName: !Join
        - '-'
        - - !Ref AWS::StackName
          - "job"
          - "mainprocess"
      ContainerProperties:
        Image: !Ref MainImage
        Vcpus: 8
        Memory: 8000
        Command:
          - python
          - input_to_database.py
          - main
        Volumes:
          - Host:
              SourcePath: "/home/ec2-user/.synapseCache"
            Name: synapsecache
        MountPoints:
          - ContainerPath: "/root/.synapseCache"
            ReadOnly: false
            SourceVolume: synapsecache

Outputs:
  BatchComputeEnvironment:
    Value: !Ref BatchComputeEnvironment
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-BatchComputeEnvironment'
  BatchJobQueue:
    Value: !Ref BatchJobQueue
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-BatchJobQueue'
  MainBatchJob:
    Value: !Ref MainBatchJob
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-MainBatchJob'
